// STOCKS
export const SET_MOST_ACTIVE_STOCKS = "STOCKS/SET_MOST_ACTIVE_STOCKS";
export const SET_ALL_AVAILABLE_STOCKS = "STOCKS/SET_ALL_AVAILABLE_STOCKS";
export const SET_ACTIVE_STOCK = "STOCKS/SET_ACTIVE_STOCK";
export const SET_STOCK_NEWS = "STOCKS/SET_STOCK_NEWS";

// USER
export const SET_USER_STOCKS = "USER/SET_USER_STOCKS";
export const ADD_STOCK = "USER/ADD_STOCK";
export const REMOVE_STOCK = "USER/REMOVE_STOCK";

// UI
export const ADD_STOCK_TO_RECENTLY_VIEWED = "UI/ADD_STOCK_TO_RECENTLY_VIEWED";
export const SET_DROPDOWN_IS_VISIBLE = "UI/SET_DROPDOWN_IS_VISIBLE";
